<SearchScreen>:
    GridLayout:
        cols:1
        padding: 
        Image:
            id: img
            size_hint_y: 0.8
        TextInput: 
            id:user_query
            size_hint_y: 0.1
        Button:
            text: 'Search Image'
            size_hint_y: 0.1
            on_press: root.search_image()
        
<RootWidget>:
    SearchScreen:
        id:search_screen
        name: 'search screen'